##########
# UNCOMMENT IF YOU'RE USING TERMUX:
# - Manually specify the path to your SDK's aapt2
# - Replace the build tools version (35.0.1) to match buildToolsVersion in gradle.build.kts
# - Required because AGP only provides x86 binaries, while Termux (ARM) needs
#   to use the aapt2 compiled for your architecture from local SDK
# android.aapt2FromMavenOverride=/data/data/com.termux/files/home/Android/Sdk/build-tools/35.0.1/aapt2

# Colored output
org.gradle.console=rich

# CMake verbose
android.native.buildOutput=verbose

# More RAM for Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
